use dblojinha;

CREATE TABLE PRODUTOS (
[CODIGO] [INT] IDENTITY (1,1) NOT NULL,
    NOME VARCHAR(100),
    PRECO DECIMAL(10,2),
    ESTOQUE INT,
CONSTRAINT [PK_PRODUTOS] PRIMARY KEY CLUSTERED
(
    [CODIGO]
    ) ON [PRIMARY]
) ON [PRIMARY]
GO

INSERT INTO PRODUTOS (NOME, PRECO, ESTOQUE)
VALUES('Computador Gamer', 15000.00, 15);

INSERT INTO PRODUTOS (NOME, PRECO, ESTOQUE)
VALUES('Impressora 3D', 5000.00, 10);

SELECT * FROM PRODUTOS;
 



