use dblojinha;

CREATE TABLE CLIENTES (
[CODIGO] [INT] IDENTITY (1,1) NOT NULL,
    NOME VARCHAR(100),
    EMAIL VARCHAR(100),
    TELEFONE VARCHAR(20),
CONSTRAINT [PK_CLIENTES] PRIMARY KEY CLUSTERED
(
    [CODIGO]
    ) ON [PRIMARY]
) ON [PRIMARY]
GO

INSERT INTO CLIENTES(NOME, EMAIL, TELEFONE)
VALUES ('Joana Carolina','jclitha21@gmail.com','+55(69)99354-8436');

INSERT INTO CLIENTES(NOME, EMAIL, TELEFONE)
VALUES ('Maria Helena','mariahelen@gmail.com','+55(69)98116-6616');

SELECT * FROM CLIENTES;


